
tests:
	./lab2 jar.bmp jar_1.bmp .1
	./lab2 jar.bmp jar_2.bmp 3.0

	./lab2 flowers.bmp flowers_1.bmp .20
	./lab2 flowers.bmp flowers_2.bmp 4.0

	./lab2 lion.bmp lion_1.bmp .30
	./lab2 lion.bmp lion_2.bmp 5.0

	./lab2 tunnel.bmp tunnel_1.bmp .50
	./lab2 tunnel.bmp tunnel_2.bmp 7.0

	./lab2 wolf.bmp wolf_1.bmp .70
	./lab2 wolf.bmp wolf_2.bmp 5.0

clean:
	rm jar_*
	rm flowers_*
	rm lion_*
	rm tunnel_*
	rm wolf_*
