
tests:
	./lab2 jar.bmp jar_1.bmp .10
	./lab2 jar.bmp jar_2.bmp 3.0

	./lab2 flowers.bmp flowers_1.bmp .20
	./lab2 flowers.bmp flowers_2.bmp 4.0

	./lab2 lion.bmp lion_1.bmp .30
	./lab2 lion.bmp lion_2.bmp 5.0

	./lab2 tunnel.bmp tunnel_1.bmp .50
	./lab2 tunnel.bmp tunnel_2.bmp 7.0

	./lab2 wolf.bmp wolf_1.bmp .70
	./lab2 wolf.bmp wolf_2.bmp 5.0

clean:
	rm -f jar_*
	rm -f flowers_*
	rm -f lion_*
	rm -f tunnel_*
	rm -f wolf_*
