
tests:
	./lab3 jar.bmp 1.0, 0.5, 0.5 jar_blue.bmp
	./lab3 jar.bmp 0.5, 1.0, 0.5 jar_green.bmp
	./lab3 jar.bmp 0.5, 0.5, 1.0 jar_red.bmp
	./lab3 jar.bmp 0.9, 1.0, 0.93 jar_matrix.bmp

	./lab3 flowers.bmp 1.0, 0.5, 0.5 flowers_blue.bmp
	./lab3 flowers.bmp 0.5, 1.0, 0.5 flowers_green.bmp
	./lab3 flowers.bmp 0.5, 0.5, 1.0 flowers_red.bmp
	./lab3 flowers.bmp 0.9, 1.0, 0.93 flowers_matrix.bmp

	./lab3 lion.bmp 1.0, 0.5, 0.5 lion_blue.bmp
	./lab3 lion.bmp 0.5, 1.0, 0.5 lion_green.bmp
	./lab3 lion.bmp 0.5, 0.5, 1.0 lion_red.bmp
	./lab3 lion.bmp 0.9, 1.0, 0.93 lion_matrix.bmp

	./lab3 tunnel.bmp 1.0, 0.5, 0.5 tunnel_blue.bmp
	./lab3 tunnel.bmp 0.5, 1.0, 0.5 tunnel_green.bmp
	./lab3 tunnel.bmp 0.5, 0.5, 1.0 tunnel_red.bmp
	./lab3 tunnel.bmp 0.9, 1.0, 0.93 tunnel_matrix.bmp

	./lab3 wolf.bmp 1.0, 0.5, 0.5 wolf_blue.bmp
	./lab3 wolf.bmp 0.5, 1.0, 0.5 wolf_green.bmp
	./lab3 wolf.bmp 0.5, 0.5, 1.0 wolf_red.bmp
	./lab3 wolf.bmp 0.9, 1.0, 0.93 wolf_matrix.bmp

clean:
	rm -f jar_*
	rm -f flowers_*
	rm -f lion_*
	rm -f tunnel_*
	rm -f wolf_*
