
tests:
	./assignment_2 jar.bmp wolf.bmp 0.5 jar_wolf.bmp
	./assignment_2 jar.bmp flowers.bmp 0.5 jar_flowers.bmp
	./assignment_2 jar.bmp lion.bmp 0.5 jar_lion.bmp
	./assignment_2 jar.bmp tunnel.bmp 0.5 jar_tunnel.bmp

	./assignment_2 flowers.bmp wolf.bmp 0.5 flowerwolf.bmp
	./assignment_2 flowers.bmp lion.bmp 0.5 flowerlion.bmp
	./assignment_2 flowers.bmp tunnel.bmp 0.5 flowertunnel.bmp

	./assignment_2 lion.bmp wolf.bmp 0.5 lionwolf.bmp
	./assignment_2 lion.bmp tunnel.bmp 0.5 tunnnellion.bmp

	./assignment_2 tunnel.bmp wolf.bmp 0.5 tunnelwolf.bmp
	

clean:
	rm -f jar_*
	rm -f flowers_*
	rm -f lion_*
	rm -f tunnel_*
	rm -f wolf_*
