
tests:
	./assignment_2 jar.bmp wolf.bmp 0.3 jar_1.bmp
	./assignment_2 jar.bmp flowers.bmp 0.3 jar_2.bmp
	./assignment_2 jar.bmp lion.bmp 0.3 jar_3.bmp
	./assignment_2 jar.bmp tunnel.bmp 0.3 jar_4.bmp

	./assignment_2 flowers.bmp jar.bmp 0.3 flowers_1.bmp
	./assignment_2 flowers.bmp lion.bmp 0.3 flowers_2.bmp
	./assignment_2 flowers.bmp tunnel.bmp 0.3 flowers_3.bmp
	./assignment_2 flowers.bmp wolf.bmp 0.3 flowers_4.bmp

	./assignment_2 lion.bmp flowers.bmp 0.3 lion_1.bmp
	./assignment_2 lion.bmp jar.bmp 0.3 lion_2.bmp
	./assignment_2 lion.bmp tunnel.bmp 0.3 lion_3.bmp
	./assignment_2 lion.bmp wolf.bmp 0.3 lion_4.bmp

	./assignment_2 tunnel.bmp flowers.bmp 0.3 tunnel_1.bmp
	./assignment_2 tunnel.bmp jar.bmp 0.3 tunnel_2.bmp
	./assignment_2 tunnel.bmp lion.bmp 0.3 tunnel_3.bmp
	./assignment_2 tunnel.bmp wolf.bmp 0.3 tunnel_4.bmp

	./assignment_2 wolf.bmp flowers.bmp 0.3 wolf_1.bmp
	./assignment_2 wolf.bmp jar.bmp 0.3 wolf_2.bmp
	./assignment_2 wolf.bmp lion.bmp 0.3 wolf_3.bmp
	./assignment_2 wolf.bmp tunnel.bmp 0.3 wolf_4.bmp
	

clean:
	rm -f jar_*
	rm -f flowers_*
	rm -f lion_*
	rm -f tunnel_*
	rm -f wolf_*
